#첫째 줄에 (A+B)%C, 둘째 줄에 (A%C + B%C)%C, 셋째 줄에 (A×B)%C, 넷째 줄에 (A%C × B%C)%C를 출력한다
a, b, c = input().split(' ')
a = int(a)
b = int(b)
c = int(c)
one = int((a+b)%c)
two = int((a%c+b%c)%c)
three = int((a*b)%c)
four = int((a%c*b%c)%c)
print(one)
print(two)
print(three)
print(four)
