-- 코드를 입력하세요
SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
from ANIMAL_INS as INS join ANIMAL_OUTS as OUTS using(ANIMAL_ID)
where INS.SEX_UPON_INTAKE != OUTS.SEX_UPON_OUTCOME
order by OUTS.ANIMAL_ID